# Generated by Django 6.0 on 2025-12-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patient',
            name='age_type',
            field=models.CharField(choices=[('years', 'سنة'), ('months', 'شهر'), ('days', 'يوم')], default='years', help_text='اختر وحدة العمر', max_length=10, verbose_name='نوع العمر'),
        ),
        migrations.AddField(
            model_name='patient',
            name='age_value',
            field=models.PositiveIntegerField(default=0, help_text='أدخل العمر', verbose_name='قيمة العمر'),
        ),
    ]
