# Generated by Django 6.0 on 2025-12-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_patient_date_of_birth_patient_age_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل الاسم الكامل للطبيب', max_length=200, verbose_name='اسم الطبيب')),
                ('specialty', models.CharField(blank=True, help_text='مثال: باطنية، أطفال، جراحة', max_length=100, null=True, verbose_name='التخصص')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف العيادة')),
                ('clinic_address', models.TextField(blank=True, null=True, verbose_name='عنوان العيادة')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الرخصة الطبية')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('notes', models.TextField(blank=True, help_text='أي معلومات إضافية عن الطبيب', null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, help_text='هل الطبيب لا يزال يعمل مع المختبر؟', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الأطباء',
                'ordering': ['name'],
            },
        ),
    ]
