# Generated by Django 6.0 on 2025-12-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='referring_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.doctor', verbose_name='الطبيب المحوّل'),
        ),
    ]
