# Generated by Django 6.0 on 2025-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_referring_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التحليل (إنجليزي)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم التحليل (عربي)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود التحليل')),
                ('result_type', models.CharField(choices=[('numerical', 'رقمي'), ('text_positive_negative', 'نصي (موجب/سالب)'), ('culture', 'مزرعة'), ('microscopy', 'فحص مجهري'), ('text_general', 'نصي عام')], default='numerical', max_length=50)),
                ('sample_type', models.CharField(choices=[('blood', 'دم'), ('serum', 'سيروم'), ('plasma', 'بلازما'), ('urine', 'بول'), ('stool', 'براز'), ('csf', 'سائل نخاعي'), ('other', 'أخرى')], default='blood', max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوحدة')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر التحليل')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='التكلفة')),
                ('turnaround_time', models.CharField(default='24 ساعة', max_length=100, verbose_name='مدة التنفيذ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف التحليل')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات التحضير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تحليل',
                'verbose_name_plural': 'التحاليل',
                'ordering': ['category', 'name'],
            },
        ),
    ]
