# Generated by Django 6.0 on 2025-12-28 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_labtest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('collected', 'تم سحب العينة'), ('in_progress', 'قيد التحليل'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الخصم')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('credit_card', 'بطاقة ائتمان'), ('insurance', 'تأمين'), ('bank_transfer', 'تحويل بنكي')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('pending', 'لم يتم الدفع'), ('partial', 'دفع جزئي'), ('paid', 'مدفوع بالكامل')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.patient', verbose_name='المريض')),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.doctor', verbose_name='الطبيب المحول')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر المطبق')),
                ('test_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التحليل'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة التحليل')),
                ('result_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='النتيجة')),
                ('result_status', models.CharField(blank=True, choices=[('normal', 'طبيعي'), ('abnormal', 'غير طبيعي'), ('critical', 'حرج')], max_length=20, null=True, verbose_name='حالة النتيجة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labtest', verbose_name='التحليل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تفصيل طلب',
                'verbose_name_plural': 'تفاصيل الطلبات',
                'unique_together': {('order', 'lab_test')},
            },
        ),
    ]
